-- Proposed ILoveSurprises catalog schema. Review in staging before production.
create table if not exists products (
  product_id text primary key,
  handle text unique not null,
  title text,
  description_html text,
  vendor text,
  product_category text,
  type text,
  tags text,
  published boolean,
  gift_card boolean,
  seo_title text,
  seo_description text,
  status text,
  base_price numeric,
  base_compare_at_price numeric
);

create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id text not null references products(product_id) on delete cascade,
  image_url text not null,
  position integer,
  alt_text text,
  unique(product_id, image_url)
);

create table if not exists product_options (
  option_key text primary key,
  product_id text not null references products(product_id) on delete cascade,
  position integer not null,
  source_name text,
  canonical_name text
);

create table if not exists product_option_values (
  id bigint generated by default as identity primary key,
  option_key text not null references product_options(option_key) on delete cascade,
  product_id text not null references products(product_id) on delete cascade,
  position integer,
  source_name text,
  canonical_name text,
  value text
);

create table if not exists product_variants (
  variant_key text primary key,
  product_id text not null references products(product_id) on delete cascade,
  sku text,
  barcode text,
  price numeric,
  compare_at_price numeric,
  option1_name text,
  option1_value text,
  option2_name text,
  option2_value text,
  option3_name text,
  option3_value text,
  grams numeric,
  weight_unit text,
  inventory_tracker text,
  inventory_policy text,
  fulfillment_service text,
  requires_shipping boolean,
  taxable boolean,
  tax_code text,
  cost_per_item numeric,
  variant_image text
);

create table if not exists collections (
  collection_id text primary key,
  handle text unique not null,
  title text,
  body_html text,
  sort_order text,
  template_suffix text,
  updated_at timestamptz,
  image_src text,
  image_alt_text text,
  products_count integer,
  source_type text,
  source_title text,
  source_description text,
  inclusion_type text,
  inclusion_match text,
  published_online_store boolean,
  published_at_online_store timestamptz,
  seo_title text,
  seo_description text,
  smartseo_title text,
  smartseo_description text,
  smartseo_keywords text
);

create table if not exists collection_conditions (
  id bigint generated by default as identity primary key,
  collection_id text not null references collections(collection_id) on delete cascade,
  collection_handle text,
  command text,
  field text,
  relation text,
  value text,
  match text
);

create table if not exists product_collections (
  collection_id text not null references collections(collection_id) on delete cascade,
  product_id text not null references products(product_id) on delete cascade,
  position integer,
  mapping_source text,
  primary key (collection_id, product_id)
);

create table if not exists product_metafields (
  id bigint generated by default as identity primary key,
  product_id text not null references products(product_id) on delete cascade,
  metafield_column text,
  value text
);

create table if not exists collection_metafields (
  id bigint generated by default as identity primary key,
  collection_id text not null references collections(collection_id) on delete cascade,
  metafield_column text,
  value text
);

create index if not exists idx_product_images_product on product_images(product_id);
create index if not exists idx_product_variants_product on product_variants(product_id);
create index if not exists idx_product_collections_product on product_collections(product_id);
create index if not exists idx_product_collections_collection on product_collections(collection_id);
